### ISSUE TITLE
edit jsona nie działa :(

### ISSUE THREAD

**Issue by Huehueh** [Betrezen88/NeuroshimaCardManager#1]

**Comment by michal2229** [comment]
mi działa

**Comment by Betrezen88** [comment]
@Huehueh jakby można było prosić o json, który był edytowany i sprawiał problemy, ewentualnie sprawdzić poprawność jsona za pomocą onlinowego parsera.

**Comment by Betrezen88** [comment]
Zamykam z powodu nie dostarczenia wymaganych danych.
