### ISSUE TITLE
[feature_request] skróty klawiszowe, np. ctrl+s

### ISSUE THREAD

**Issue by michal2229** [Betrezen88/NeuroshimaCardManager#3]

**Comment by Betrezen88** [comment]
Elo mordeczko, ogarnięte, te funkcje, które działają, mają również skrót klawiszowy. Zastanawiam się nad dodaniem status bara, gdzie będę umieszczał info o sukcesie, w razie błędu, poleci okno z błędem, co o tym myślisz ?
